[main]
  serialize = "{version}-{banner}"
  tag = false
  version = "1.2.0"

[[operate]]
  location = "pyproject.toml"
  replace = "version = \"{}\""
  search = "version = \"{}\""

[[operate]]
  location = "README.md"
  replace = "Current version: **{}**"
  search = "Current version: **{}**"